### ISSUE TITLE
The app counts the dashboard and full screen app as a desktop

### ISSUE THREAD

**Issue by Vafa-Andalibi** [gechr/WhichSpace#11]
Is it supposed to behave like this? I think it doesn't hurt if you add a option to change this behavior and just show the actual "Desktop" number

**Comment by gechr** [comment]
> Is it supposed to behave like this?

Yeah, the purpose of this app is to display the space numbers to help navigate between them more easily. I wouldn't mind adding some options to help you filter out unwanted spaces, but I'm not sure it's a feature other people would use and I don't really have the time at the moment (would welcome any PRs!)

Here are a couple of links which may shed some light on the space situation:
- https://www.askdavetaylor.com/how_to_remove_dashboard_as_a_space_in_mac_os_x_spaces/
- https://www.quora.com/Why-do-full-screen-Mac-apps-create-their-own-desktop-space
