### ISSUE TITLE
Which Space counts FullScreen apps as Spaces

### ISSUE THREAD

**Issue by BracketMaster** [gechr/WhichSpace#12]
It would be nice if there was an option to not count apps in fullscreen mode as spaces. For example, I often fullscreen my terminal and stick it between the first and third space. If I need to switch to the third space I must press ctrl+2. It would be nice if "whichspace" provivded an option to not count fullscreen spaces so ctrl+n matches with what "whichspace" displays as the nth space.

**Comment by l-Marty-l** [comment]
I agree, same applies to the dashboard, if you decide to give it a space.

<img width="670" alt="Screenshot 2019-07-03 at 17 31 59" src="https://user-images.githubusercontent.com/24259245/60604756-8b697b80-9db8-11e9-92ad-cf0b66c93a3f.png">

**Comment by Hritik14** [comment]
@gechr Can we reopen this issue? It originally asked for an option to choose if we want fullscreen apps as spaces. I use yabai and yabai by default counts fullscreen apps as spaces and I would like it to remain that way.
