### ISSUE TITLE
Feature suggestion: space title

### ISSUE THREAD

**Issue by ailaG** [gechr/WhichSpace#17]
Suggestion: allow users to set and change titles for spaces.
For example, if I'm working on two projects in two spaces, say "work" and "side project", I could enter that somewhere and have WhichSpace show my spaces as "1 - work" and "2 - side project" rather than "1" and "2".

Thanks

**Comment by gechr** [comment]
I'm not _entirely_ convinced this feature is something that is suitable in a menubar application, given the limited horizontal space available in the menubar. That said, I do appreciate different people have different tastes and it's down to the end-user to make that decision for themselves.

I'm going to close this for now as I think it's slightly out of the original scope of this project, but I'll keep it in the back of my mind and reopen if I have a change of heart. 😄
