### ISSUE TITLE
Feature Request - Make Space Number Available via AppleScript

### ISSUE THREAD

**Issue by jsauerconsult** [gechr/WhichSpace#18]
WhichSpace is great! Thank you for sharing it. I have over 10 spaces set up on my MBP and I'd get lost without WhichSpace. 😉

It would be great if WhichSpace made the SpaceNumber available via AppleScript (or some other means). I'm not a macOS programmer, but maybe the easiest way would be to write the space number to a text file in the Library (just a thought). 

I use Keyboard Maestro to switch spaces. If the space number was available, I could save the number and then create a macro that would allow me to easily toggle between two spaces.

Thanks for considering my request. Again, thanks for sharing WhichSpace!

**Comment by gechr** [comment]
Thank you for the kind words! 😁

Assuming I correctly understand your intention, if all you want to do is switch between spaces using keybinds, I don't think you need to use a tool like Keyboard Maestro, macOS has native support for it under **System Preferences → Keyboard → Shortcuts → Mission Control**

![image](https://user-images.githubusercontent.com/7656560/92835862-af204c80-f3d3-11ea-9521-f9539d8d1b06.png)

**Comment by StevenJPx2** [comment]
I think it's safe to close this.

**Comment by jsauerconsult** [comment]
@gechr, thanks so much for the quick reply! 

Sorry I should have described my scenario more clearly. Yes, I use the keyboard shortcuts that you point out. However, because I have configured more than 10 spaces, I can sometimes forget which app (or combination of apps) I have assigned to a given space. Thankfully, __Keyboard Maestro__ provides a simple way to display palettes.

<img width="247" alt="Spaces Palette" src="https://user-images.githubusercontent.com/59451100/92947860-8e351700-f426-11ea-9635-6df6d1d65b75.png">

So here's the way I generally work: a) press a keyboard shortcut to display the above pallet, then b) press a single key to move to the desired space. For example, suppose I'm working with Safari (5) and I want to move to move to BBEdit (9) but I've forgotten that it's in space 9. I just press <kbd>Ctrl+Opt+P</kbd>, take a quick glance at the palette, then press <kbd>9</kbd>. Note that I've assigned BBedit to Desktop 9.

<img width="521" alt="BBEdit - Space 9" src="https://user-images.githubusercontent.com/59451100/92951719-d7886500-f42c-11ea-9c06-3b44efe50492.png">

What I'd like to do is have another macro to return to the previously displayed space. If I had access to a space number, the macro behind the palette could save that value to a Keyboard Maestro global variable _before_ switching to the new space. Then the new _Toggle Space_ macro could read that value and switch back to the original space. For reference, here's a simplified version of the macro _behind_ the BBEdit palette item.

<img width="437" alt="BBedit" src="https://user-images.githubusercontent.com/59451100/92950271-65168580-f42a-11ea-8394-ef6eb04a7687.png">

Note that the macro uses keystrokes to switch spaces. This is done because according to the Keyboard Maestro developer, Peter N Lewis, Apple does not provide a way to do it with a Public API.

Note for the sake of discussion here, I've simplified my typical scenarios. I have more complex macros that automatically switch to new spaces. Again, with these macros it would be very helpful to _read and save_ the space number before moving to other spaces so that the original space could be restored after a series of macro actions.

Again, thanks for sharing __WhichSpace__!

**Comment by gechr** [comment]
Aha, thanks for the detailed explanation, I understand now.

The good news is, I don't think I need to change anything in WhichSpace for you to be able to get the space number from the menubar icon directly, although I can't guarantee this will continue to work for future releases of WhichSpace, or even macOS!

Based on [this StackOverflow answer](https://stackoverflow.com/a/29702254), I came up with the following, which returns the number displayed in WhichSpace's menubar icon:

```
$ osascript -e 'tell application "System Events" to tell process "WhichSpace" to title of menu bar items of menu bar 1'
3
```

Let me know if this works for you!

**Comment by jsauerconsult** [comment]
That works perfectly. I've seen that AppleScript technique before; I should have thought of that myself.

Thanks for taking the time to help me out. I plan to share this with the Keyboard Maestro community, thus I suspect you'll be seeing more WhichSpace downloads. Here's the macro that I will call at the beginning of many others.

![Set SpaceNo](https://user-images.githubusercontent.com/59451100/92985833-50ff7200-f484-11ea-807f-1da746cb7392.jpg)

**Comment by gechr** [comment]
Fantastic, I’m glad I could help! 😄
