### ISSUE TITLE
Show workspace number correct if multiple screens are used

### ISSUE THREAD

**Issue by alexus37** [gechr/WhichSpace#27]
Hi,
first thanks for the very helpful tool.
I want to report a bug/ make a feature request: 
I am using 2 monitors connected to my mac and move windows mostly by command shortcuts. 
However, `whichspace` always shows the number of the current workspace.

Is it possible to show the workspace number of the current workspace shown on the screen?
Eg. Monitor 1 shows workspace 1 and monitor 2 shows workspace 2. 
(currently, both monitors show the same workspace number)

**Comment by gechr** [comment]
https://github.com/gechr/WhichSpace/issues/24
