### ISSUE TITLE
Center the number in the menu bar icon

### ISSUE THREAD

**Issue by niyue** [gechr/WhichSpace#31]
Currently, the space number shown in the menu bar is not central aligned, which makes it (or makes me) feeling the app not rendering the position correctly. Is there any way we could make this number `1`/`2`/etc central aligned in the gray box? Thanks.

<img width="164" alt="image" src="https://user-images.githubusercontent.com/27754/150662268-fe9bb5bd-6edf-464c-b4b1-e4ecc88eb3c8.png">

I am not sure if this is a bug, and the screenshot posted in the github repo seems correct and the number `4` is central aligned in the picture
<img src="https://camo.githubusercontent.com/5a42786926e5a54fced297ab5a1bb161a002e594beeb4d36a68af8e44562ca7e/68747470733a2f2f7261772e6769746875622e636f6d2f67656368722f576869636853706163652f6d61737465722f53637265656e73686f74732f576869636853706163652e706e67"/>

**Comment by gechr** [comment]
https://github.com/gechr/WhichSpace/issues/20
