### ISSUE TITLE
External monitor spaces

### ISSUE THREAD

**Issue by cuth** [gechr/WhichSpace#4]
This is a great app, very simple, exactly what I was looking for!

My only issue is that my external monitor displays the space number of my primary monitor. It would be nice if the status bar could display different numbers on the primary and secondary monitor but that might not be possible. If not, could we at least show the space number for whatever space is the active space?

**Comment by gechr** [comment]
Hah, yeah, aware of this.

It's listed as a TODO in the README, but have never got around to implementing it as I personally only use one monitor.

I'll revisit soon! (PRs welcome in the meantime)

**Comment by cuth** [comment]
Oops, yep, it is in the README. Thanks! I can look into this as well but I'm completely new to Mac OS development.

**Comment by nuynait** [comment]
I added a secondary menu item for the secondary monitor if exists. If you want this behavior you can download from my fork:

https://github.com/nuynait/WhichSpace

**Comment by gechr** [comment]
This is now released in v0.3.0 - https://github.com/gechr/WhichSpace/pull/16

Thanks to @tidues!
