### ISSUE TITLE
Number on the menu bar icon doesn't match the desktop number

### ISSUE THREAD

**Issue by sitnikovme** [gechr/WhichSpace#5]
For example, on the "Desktop 1" I see number 2 on the icon and  so on.

**Comment by 1aGh** [comment]
I have same problem, i have two monitors. And on each monitor i have 3 spaces, on monitor 1 a have spaces 1,2,3 and on monitor 2 i have spaces 4,5,6. But WhichSpace show on both monitor the same number but it always show only number from monitor 1. So if i change space on monitor 2 from 4 to 5 and i'm on monitor 1 on space 1 it keep showing number 1 on monitor 2.

**Comment by metyl** [comment]
@1aGh this is the same problem as in #4 it would be nice to have it implemented.

**Comment by gechr** [comment]
Yep, @metyl is right – closing this in favour of #4.

Unfortunately, I don't have an ETA on when I'll get around to looking at it, super busy at the moment!
