### ISSUE TITLE
Downloadable `app.zip` seems to be corrupted, doesn't work on Mac OS Sierra

### ISSUE THREAD

**Issue by jcham** [gechr/WhichSpace#6]

**Comment by wang0109** [comment]
Yeah. Found the same problem.

**Comment by ldstevens** [comment]
Same for me with 0.2.0

**Comment by gechr** [comment]
Can you provide some more information on the error you guys are experiencing, e.g. a screenshot?

**Comment by retronym** [comment]
![image](https://cloud.githubusercontent.com/assets/65551/23587005/ee931bda-01ed-11e7-9627-4041eae020f5.png)

**Comment by gechr** [comment]
Would you mind following [these instructions](http://osxdaily.com/2016/09/27/allow-apps-from-anywhere-macos-gatekeeper/) and seeing if it fixes the issue?

**Comment by Capyvara** [comment]
@gechr following this instruction fixes the problem.

Unless you become a "registered developer", I think it's worth to put that in the README

**Comment by gechr** [comment]
@Capyvara I am a member of the Apple Developer Program, I just think there was an issue with the profile I was using to sign the application.

I think I've fixed it now, but the update steps are slightly convoluted as a result. Could you try the following:
1. Manually download and extract [v0.2.1](https://github.com/gechr/WhichSpace/releases/download/v0.2.1/WhichSpace.app.zip)
2. Move the extracted application `/Applications/WhichSpace.app` (overwriting any previous versions you may have)
3. Launch the application (and hopefully it will prompt you to update to v0.2.2 automatically)

Let me know if you have any issues!

**Comment by gechr** [comment]
@Capyvara I am a member of the Apple Developer Program – the issue was with the way I was creating the zip archive (symlinks weren't being preserved).

I think I've fixed it now. Can you try downloading [v0.2.1](https://github.com/gechr/WhichSpace/releases/download/v0.2.1/WhichSpace.zip) and letting me know if it's fixed?

**Comment by Capyvara** [comment]
@gechr Seems to be working! but I don't know if it may be related to the previous install.

**Comment by ldstevens** [comment]
Thanks, works for me!

**Comment by gechr** [comment]
Awesome!
